name = "code-reviewer"
main = "src/index.ts"
compatibility_date = "2024-03-28"

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"

# Bind a KV namespace (optional)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Use the newer node.js compatibility flag
compatibility_flags = ["nodejs_compat"]